Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/LineLength:
  Max: 160

Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
